#!/usr/bin/env node
/**
 * bulk_wave5_fix.mjs — Wave 5 long-tail pattern-based bulk-fix mechanism (prototype).
 *
 * Purpose:
 *   Wave 5 targets 53 Tier C slugs (<= 2 baseline entries each) with a small set of
 *   repeating drift patterns. Dispatching a per-slug agent for each slug is
 *   wasteful; instead this script enumerates candidate edits across all same-pattern
 *   slugs in one run so a reviewer can approve/reject them in bulk.
 *
 * Design constraints:
 *   - `--dry-run` is DEFAULT. `--apply` must be passed explicitly to write.
 *   - The script NEVER "fixes" a segment without a high-confidence pattern match.
 *   - All content candidates are surfaced as
 *     `{ slug, file, line, kind, before, after, reason }` records so the reviewer
 *     can see exactly what the rewrite would do before approving.
 *   - The script reads `parity-check-status.json` (generated by `npm run check:parity`)
 *     for live drift state, and `parity-baseline.json` for Wave 5 slug membership.
 *   - Only the three patterns prototyped in
 *     the wave5 pattern inventory are implemented
 *     (generic-english-residue / url-verbatim / ja-extra-intro-paragraph). The other
 *     four pattern families stay deferred until follow-up PRs.
 *
 * Usage:
 *   node scripts/bulk_wave5_fix.mjs --pattern=<name> [--slug=<csv>] [--apply] [--json]
 *   # default is --dry-run (explicit flag also accepted)
 *
 * Exit codes:
 *   0 — dry-run completed (or apply succeeded)
 *   1 — CLI / IO error
 *   2 — pattern not recognized
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const THIS_FILE = fileURLToPath(import.meta.url);
const THIS_DIR = dirname(THIS_FILE);
const ROOT = join(THIS_DIR, '..');

// ---------------------------------------------------------------------------
// CLI parsing — intentionally minimal, no third-party dependency.
// ---------------------------------------------------------------------------

export function parseCliArgs(argv) {
  const opts = {
    pattern: null,
    slugs: null,
    apply: false,
    dryRun: true,
    json: false,
  };
  for (const raw of argv) {
    if (raw === '--apply') {
      opts.apply = true;
      opts.dryRun = false;
      continue;
    }
    if (raw === '--dry-run') {
      opts.apply = false;
      opts.dryRun = true;
      continue;
    }
    if (raw === '--json') {
      opts.json = true;
      continue;
    }
    const eq = raw.indexOf('=');
    if (eq < 0) continue;
    const key = raw.slice(0, eq);
    const value = raw.slice(eq + 1);
    if (key === '--pattern') opts.pattern = value;
    else if (key === '--slug' || key === '--slugs') {
      opts.slugs = value
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean);
    }
  }
  return opts;
}

// ---------------------------------------------------------------------------
// Data-layer helpers — pure functions, no side effects, safe to unit-test.
// ---------------------------------------------------------------------------

export const WAVE5_MAX_ENTRIES = 2;

/** Group baseline entries by slug -> Map<slug, entry[]> (immutable return). */
export function groupBaselineBySlug(baseline) {
  const bySlug = new Map();
  for (const entry of baseline.entries ?? []) {
    const bucket = bySlug.get(entry.slug) ?? [];
    bySlug.set(entry.slug, [...bucket, entry]);
  }
  return bySlug;
}

/** Return the sorted list of Wave 5 slugs (<= WAVE5_MAX_ENTRIES entries). */
export function selectWave5Slugs(baseline) {
  const grouped = groupBaselineBySlug(baseline);
  const slugs = [];
  for (const [slug, entries] of grouped.entries()) {
    if (entries.length <= WAVE5_MAX_ENTRIES) slugs.push(slug);
  }
  return slugs.sort();
}

/** Build slug -> status-file record map for quick lookup. */
export function indexStatusBySlug(status) {
  const idx = new Map();
  for (const file of status.files ?? []) {
    const slug = file.file.replace(/^src\/content\/docs\//, '').replace(/\.md$/, '');
    idx.set(slug, file);
  }
  return idx;
}

/** Filter the Wave 5 slug set by an optional CLI --slug list. */
export function applySlugFilter(slugs, filter) {
  if (!filter || filter.length === 0) return slugs;
  const allow = new Set(filter);
  return slugs.filter((s) => allow.has(s));
}

// ---------------------------------------------------------------------------
// Pattern registry — each handler is pure and returns candidates without
// mutating inputs. `candidate.apply()` is the only function that writes.
// ---------------------------------------------------------------------------

/**
 * @typedef {Object} BulkFixCandidate
 * @property {string} pattern
 * @property {string} slug
 * @property {string} file            Absolute file path
 * @property {number|null} line       1-based line number (null if whole-block action)
 * @property {string} kind            segmentKind hint ('paragraph' | 'ordered-list-item' | ...)
 * @property {string} before          Current JA text (for diff display)
 * @property {string} after           Proposed JA text (for diff display)
 * @property {string} reason          Human-readable justification
 * @property {number} confidence      0.0–1.0, 1.0 = deterministic mechanical
 * @property {(content:string) => string} apply  Returns updated content
 */

/** Escape a literal string for use inside a RegExp. */
function escapeRegex(literal) {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// ---- Pattern A: generic-english-residue -----------------------------------

/**
 * For each actionable `segment-untranslated` issue on a Wave 5 slug, surface the
 * offending JA segment as a review candidate. The prototype does NOT attempt to
 * re-translate — it only pinpoints the segment for a human / downstream agent.
 */
export function detectGenericEnglishResidue({ slug, statusFile, jaContent, absPath }) {
  const candidates = [];
  const issues = (statusFile?.issues ?? []).filter(
    (i) => i.severity === 'actionable' && i.type === 'segment-untranslated',
  );
  if (issues.length === 0) return candidates;

  // We emit a *reporting-only* candidate per offending segment. apply() is a
  // no-op on purpose: mechanical re-translation is unsafe; the reviewer rewrites
  // the segment manually. This keeps the prototype honest about its confidence.
  for (const issue of issues) {
    candidates.push({
      pattern: 'generic-english-residue',
      slug,
      file: absPath,
      line: null,
      kind: issue.segmentKind ?? 'paragraph',
      before: `(see segment in section "${issue.sectionPath || '(preface)'}")`,
      after: '(manual rewrite required — re-translate untranslated English prose)',
      reason:
        `Classifier flagged JA ${issue.segmentKind ?? 'segment'} as containing untranslated ` +
        `English prose. Masked glossary/invariant tokens did not cover the residue.`,
      confidence: 0.0,
      apply: (content) => content,
    });
  }
  return candidates;
}

// ---- Pattern B: url-verbatim ----------------------------------------------

const URL_TOKEN_RE = /(https?:\/\/\S+|\/docs\/[\w/#-]+)/g;

/**
 * For each `segment-token-gap` issue whose missingTokens contain `/docs/...`,
 * locate any JA link whose target resembles the missing token's basename/slug,
 * and propose swapping the JA target to the verbatim EN token.
 *
 * Heuristic: a JA segment has at most a handful of links; if exactly one JA link
 * is "close" (shares basename or last slug segment) to a missing EN token, we
 * propose the swap. Otherwise we emit a zero-confidence report-only candidate.
 */
export function detectUrlVerbatim({ slug, statusFile, jaContent, absPath }) {
  const candidates = [];
  const issues = (statusFile?.issues ?? []).filter(
    (i) => i.severity === 'actionable' && i.type === 'segment-token-gap',
  );
  if (issues.length === 0) return candidates;

  const lines = jaContent.split('\n');

  for (const issue of issues) {
    const missingTokens = Array.isArray(issue.missingTokens) ? issue.missingTokens : [];
    if (missingTokens.length === 0) continue;

    // Only consider /docs/... or https://... URL tokens. CLI flags and JS identifiers
    // need a different mechanism out of scope for the prototype.
    const urlTokens = missingTokens.filter((t) => t.startsWith('/docs/') || t.startsWith('http'));
    if (urlTokens.length === 0) {
      candidates.push({
        pattern: 'url-verbatim',
        slug,
        file: absPath,
        line: null,
        kind: issue.segmentKind ?? 'paragraph',
        before: `(missing non-URL tokens: ${missingTokens.join(', ')})`,
        after: '(manual restore required — non-URL invariant token missing)',
        reason:
          `segment-token-gap has no /docs or https missingTokens; likely a CLI flag ` +
          `or JS identifier. Mechanical URL swap not applicable.`,
        confidence: 0.0,
        apply: (content) => content,
      });
      continue;
    }

    // For each URL token, scan each line for a JA `/docs/` link whose path shares
    // the last slug segment with the missing token (path-only compare).
    let proposedAny = false;
    for (const enToken of urlTokens) {
      const enBasename = enToken.replace(/#.*$/, '').split('/').filter(Boolean).pop() ?? '';
      if (!enBasename) continue;

      for (let i = 0; i < lines.length; i += 1) {
        const line = lines[i];
        URL_TOKEN_RE.lastIndex = 0;
        let m;
        const matches = [];
        while ((m = URL_TOKEN_RE.exec(line)) !== null) {
          matches.push({ token: m[1], index: m.index });
        }
        for (const match of matches) {
          if (match.token === enToken) continue; // already correct
          const jaBasename = match.token.replace(/#.*$/, '').split('/').filter(Boolean).pop() ?? '';
          if (!jaBasename) continue;
          if (jaBasename.toLowerCase() !== enBasename.toLowerCase()) continue;
          proposedAny = true;
          // Confidence 0.5 because basename overlap is a strong but not deterministic
          // signal — reviewer must still confirm semantic match.
          candidates.push({
            pattern: 'url-verbatim',
            slug,
            file: absPath,
            line: i + 1,
            kind: issue.segmentKind ?? 'paragraph',
            before: match.token,
            after: enToken,
            reason:
              `JA link target "${match.token}" shares basename "${enBasename}" with missing ` +
              `EN invariant token "${enToken}". Propose verbatim swap per §5.5 Pattern 4.`,
            confidence: 0.5,
            apply: (content) => {
              const contentLines = content.split('\n');
              const targetLine = contentLines[i];
              if (typeof targetLine !== 'string') return content;
              const swapped = targetLine.replace(
                new RegExp(escapeRegex(match.token), 'g'),
                enToken,
              );
              return [
                ...contentLines.slice(0, i),
                swapped,
                ...contentLines.slice(i + 1),
              ].join('\n');
            },
          });
        }
      }
    }

    if (!proposedAny) {
      candidates.push({
        pattern: 'url-verbatim',
        slug,
        file: absPath,
        line: null,
        kind: issue.segmentKind ?? 'paragraph',
        before: `(missing tokens: ${urlTokens.join(', ')})`,
        after: '(no basename match in JA — manual URL restore required)',
        reason: `URL basename did not match any JA link in this file.`,
        confidence: 0.0,
        apply: (content) => content,
      });
    }
  }

  return candidates;
}

// ---- Pattern C: ja-extra-intro-paragraph ----------------------------------

/**
 * For each `section-structure-mismatch` where JA has exactly ONE extra
 * `paragraph` block vs. EN (same kind-multiset minus one paragraph), AND there is
 * a matching `segment-extra` of kind=paragraph in the same section, surface the
 * JA paragraph as a candidate for deletion or merge. We do not attempt to decide
 * between delete vs. merge — that requires semantic review.
 */
export function detectJaExtraIntroParagraph({ slug, statusFile, jaContent, absPath }) {
  const candidates = [];
  const issues = statusFile?.issues ?? [];
  const structureIssues = issues.filter(
    (i) => i.severity === 'actionable' && i.type === 'section-structure-mismatch',
  );
  if (structureIssues.length === 0) return candidates;

  for (const structure of structureIssues) {
    const enKinds = Array.isArray(structure.enKinds) ? structure.enKinds : [];
    const jaKinds = Array.isArray(structure.jaKinds) ? structure.jaKinds : [];
    if (jaKinds.length !== enKinds.length + 1) continue;
    if (countKind(jaKinds, 'paragraph') !== countKind(enKinds, 'paragraph') + 1) continue;
    // Every other kind count must match — i.e. exactly one paragraph is extra.
    const kinds = new Set([...enKinds, ...jaKinds]);
    let otherMatches = true;
    for (const kind of kinds) {
      if (kind === 'paragraph') continue;
      if (countKind(jaKinds, kind) !== countKind(enKinds, kind)) {
        otherMatches = false;
        break;
      }
    }
    if (!otherMatches) continue;

    // Find the paired segment-extra paragraph in the same section.
    const extraInSection = issues.find(
      (i) =>
        i.severity === 'actionable' &&
        i.type === 'segment-extra' &&
        i.segmentKind === 'paragraph' &&
        i.sectionPath === structure.sectionPath,
    );
    if (!extraInSection) continue;

    candidates.push({
      pattern: 'ja-extra-intro-paragraph',
      slug,
      file: absPath,
      line: null,
      kind: 'paragraph',
      before:
        `(JA section "${structure.sectionPath || '(preface)'}" has one extra paragraph vs. EN — ` +
        `JA kinds=[${jaKinds.join(', ')}], EN kinds=[${enKinds.join(', ')}])`,
      after:
        `(merge the extra paragraph into an adjacent block or delete if it is a JA-added ` +
        `preamble — manual decision required)`,
      reason:
        `Section structure differs by exactly one paragraph block. Canonical §5.5 ` +
        `pattern: JA added an intro paragraph absent in EN source.`,
      confidence: 0.2,
      apply: (content) => content, // deletion is semantic, not mechanical.
    });
  }

  return candidates;
}

function countKind(kinds, target) {
  let n = 0;
  for (const k of kinds) if (k === target) n += 1;
  return n;
}

// ---- Registry --------------------------------------------------------------

export const PATTERN_REGISTRY = Object.freeze({
  'generic-english-residue': detectGenericEnglishResidue,
  'url-verbatim': detectUrlVerbatim,
  'ja-extra-intro-paragraph': detectJaExtraIntroParagraph,
});

export const IMPLEMENTED_PATTERNS = Object.freeze(Object.keys(PATTERN_REGISTRY));

// ---------------------------------------------------------------------------
// Orchestration
// ---------------------------------------------------------------------------

/**
 * Core workflow: enumerate candidates for all slugs matching the pattern.
 * Separated from `main()` for unit testing.
 */
export function buildCandidates({ pattern, slugs, baseline, status, root = ROOT, fs = defaultFs }) {
  const detector = PATTERN_REGISTRY[pattern];
  if (!detector) {
    throw new Error(
      `Unknown pattern "${pattern}". Implemented: ${IMPLEMENTED_PATTERNS.join(', ')}`,
    );
  }
  const wave5 = selectWave5Slugs(baseline);
  const byStatus = indexStatusBySlug(status);
  const targetSlugs = applySlugFilter(wave5, slugs);

  const allCandidates = [];
  const perSlugSummary = [];
  for (const slug of targetSlugs) {
    const statusFile = byStatus.get(slug);
    if (!statusFile) {
      perSlugSummary.push({ slug, candidateCount: 0, reason: 'no-status-entry' });
      continue;
    }
    const absPath = join(root, 'src/content/docs', `${slug}.md`);
    if (!fs.existsSync(absPath)) {
      perSlugSummary.push({ slug, candidateCount: 0, reason: 'missing-ja-file' });
      continue;
    }
    const jaContent = fs.readFileSync(absPath, 'utf8');
    const candidates = detector({ slug, statusFile, jaContent, absPath });
    allCandidates.push(...candidates);
    perSlugSummary.push({ slug, candidateCount: candidates.length });
  }

  return { candidates: allCandidates, perSlug: perSlugSummary, pattern, total: targetSlugs.length };
}

/** Format a candidate as a short human-readable diff line. */
export function formatCandidate(c) {
  const lineHint = c.line ? `:${c.line}` : '';
  const confidence = c.confidence.toFixed(2);
  return [
    `- ${c.slug}${lineHint} [${c.kind}] (confidence=${confidence})`,
    `  pattern: ${c.pattern}`,
    `  before:  ${truncate(String(c.before), 160)}`,
    `  after:   ${truncate(String(c.after), 160)}`,
    `  reason:  ${c.reason}`,
  ].join('\n');
}

function truncate(s, n) {
  if (s.length <= n) return s;
  return `${s.slice(0, n - 1)}…`;
}

/** Default fs shim for unit tests that want to inject a virtual file system. */
const defaultFs = Object.freeze({
  readFileSync: (path, enc) => readFileSync(path, enc),
  writeFileSync: (path, content) => writeFileSync(path, content),
  existsSync: (path) => existsSync(path),
});

/** Apply high-confidence candidates to disk (only when --apply is on). */
export function applyCandidates(candidates, { fs = defaultFs, minConfidence = 0.5 } = {}) {
  // Group candidates by file so we apply all edits on the current (in-memory)
  // version of the file before writing it back. This is non-mutating at the
  // orchestration layer: each `apply()` takes content and returns new content.
  const byFile = new Map();
  for (const c of candidates) {
    if (c.confidence < minConfidence) continue;
    const bucket = byFile.get(c.file) ?? [];
    byFile.set(c.file, [...bucket, c]);
  }
  const applied = [];
  for (const [file, fileCandidates] of byFile.entries()) {
    let content = fs.readFileSync(file, 'utf8');
    for (const c of fileCandidates) {
      const next = c.apply(content);
      if (typeof next === 'string' && next !== content) {
        content = next;
        applied.push(c);
      }
    }
    fs.writeFileSync(file, content);
  }
  return applied;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

async function main() {
  const opts = parseCliArgs(process.argv.slice(2));
  if (!opts.pattern) {
    process.stderr.write(
      `usage: bulk_wave5_fix.mjs --pattern=<name> [--slug=<csv>] [--apply] [--json]\n` +
        `patterns: ${IMPLEMENTED_PATTERNS.join(', ')}\n`,
    );
    process.exit(1);
  }
  if (!IMPLEMENTED_PATTERNS.includes(opts.pattern)) {
    process.stderr.write(
      `unknown pattern: ${opts.pattern}\nimplemented: ${IMPLEMENTED_PATTERNS.join(', ')}\n`,
    );
    process.exit(2);
  }

  const baselinePath = join(ROOT, 'parity-baseline.json');
  const statusPath = join(ROOT, 'parity-check-status.json');
  if (!existsSync(statusPath)) {
    process.stderr.write(
      `parity-check-status.json not found at ${statusPath}. Run "npm run check:parity" first.\n`,
    );
    process.exit(1);
  }
  const baseline = JSON.parse(readFileSync(baselinePath, 'utf8'));
  const status = JSON.parse(readFileSync(statusPath, 'utf8'));

  const report = buildCandidates({
    pattern: opts.pattern,
    slugs: opts.slugs,
    baseline,
    status,
  });

  if (opts.json) {
    const serializable = {
      pattern: report.pattern,
      total: report.total,
      perSlug: report.perSlug,
      candidates: report.candidates.map((c) => ({
        pattern: c.pattern,
        slug: c.slug,
        file: c.file,
        line: c.line,
        kind: c.kind,
        before: c.before,
        after: c.after,
        reason: c.reason,
        confidence: c.confidence,
      })),
      dryRun: !opts.apply,
    };
    process.stdout.write(`${JSON.stringify(serializable, null, 2)}\n`);
  } else {
    process.stdout.write(
      `# Wave 5 bulk-fix candidates (pattern=${opts.pattern}, slugs=${report.total})\n`,
    );
    for (const c of report.candidates) process.stdout.write(`${formatCandidate(c)}\n\n`);
    process.stdout.write(`\nTotal candidates: ${report.candidates.length}\n`);
    process.stdout.write(`Slug coverage:\n`);
    for (const s of report.perSlug) {
      process.stdout.write(
        `  - ${s.slug}: ${s.candidateCount}${s.reason ? ` (${s.reason})` : ''}\n`,
      );
    }
  }

  if (opts.apply) {
    const applied = applyCandidates(report.candidates);
    process.stdout.write(
      `\n[APPLY] wrote ${applied.length} high-confidence edits (confidence >= 0.5).\n`,
    );
  } else {
    process.stdout.write(`\n[DRY-RUN] no files modified. Pass --apply to write.\n`);
  }
}

const isDirectInvocation =
  import.meta.url === `file://${process.argv[1]}` ||
  import.meta.url.endsWith(process.argv[1] ?? '');
if (isDirectInvocation) {
  main().catch((err) => {
    process.stderr.write(`bulk_wave5_fix: ${err.stack ?? err.message}\n`);
    process.exit(1);
  });
}
